### ISSUE TITLE
SUV computation is broken

### ISSUE THREAD

**Issue by fedorov** [paulcm/LongitudinalPETCT#4]
```
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-23795/LongitudinalPETCT/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 1237, in onEditorCollapsed
    self.__exitSegmentationMode()
  File "/Applications/Slicer.app/Contents/Extensions-23795/LongitudinalPETCT/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 1255, in __exitSegmentationMode
    self.editorWidget.exit()
  File "/Applications/Slicer.app/Contents/lib/Slicer-4.4/qt-scripted-modules/Editor.py", line 167, in exit
    self.parameterNode.RemoveObserver(self.parameterNodeTag)
AttributeError: EditorWidget instance has no attribute 'parameterNode'
```

**Comment by lassoan** [comment]
I worked on parameter nodes in scripted modules, so probably I can help with this but I would need step-by-step instructions for reproducing this issue.

**Comment by fedorov** [comment]
Andras, thank you! I looked again into this, and the error related to editor parameter node is gone. I think it might be related to another problem I had in WindowLevelEffect, which I fixed now. The next problem I see is related to VTK6 transition SetInput(). At least that one is straightforward to fix. I will try to look into this soon.

**Comment by mustafabayraktar** [comment]
Hi All;
In my end:
I followed the tracks and accepted all of them; symbolically I did :wq (written and quit) in the mentioned two files.
As expected, I still couldnt get a solution, however will work on over night.

Best 
Mustafa

**Comment by fedorov** [comment]
There seems to be an unrelated issue that affected Longitudinal PET CT extension, it will not work until this issue is resolved: http://slicer-devel.65872.n3.nabble.com/DICOM-plugins-are-not-called-td4033045.html

**Comment by fedorov** [comment]
The issue is resolved as of Dec 11, 2014, nightly build. Tested on Mac, see screenshot below.

![image](https://cloud.githubusercontent.com/assets/313942/5403397/b058c0ce-815a-11e4-8070-9a8fa0160f8e.png)
